//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MihailovaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Active = new HashSet<Active>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public int City { get; set; }
        public Nullable<int> Winner { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Active> Active { get; set; }
        public string sourceImage
        {
            get
            {
                return $"ImageEvent/{Id}.jpg";
            }
        }
        public string nameWinner
        {
            get
            {
                if (Users != null)
                {
                    return Users.FirstName;
                }
                else { return null; }
            }
        }
        public string VisibilityWinner
        {
            get
            {
                if (Users != null)
                {
                    return "Visible";
                }
                else { return "Hidden"; }
            }
        }
        public string nameCity
        {
            get
            {
                return City1.Name;
            }
        }
    }
}
